### ISSUE TITLE
PhotonCon failed too many times

### ISSUE THREAD

**Issue by qyx268** [21cmfast/21cmFAST#101] opened 2020-02-25 09:34 UTC
I'm just wondering if there is a better way to deal with this line:
https://github.com/21cmfast/21cmFAST/blob/c1214fc2cddb290a91717cc5d369c059c9dea69d/src/py21cmfast/src/ps.c#L2307

I'm running some MCMC with the photon conservation feature on. It worked at the beginning when I used small boxes {'HII_DIM':50, 'BOX_LEN':125.0} and low cadence {'Z_HEAT_MAX': 15.0, 'ZPRIME_STEP_FACTOR': 1.05} and (accidentally) started my chains with ALPHA_ESC~0.5. However, the EoR has a shape cutoff (see the orange solid line below; I have McGreer) and I suspect it is due to the large timestep... 

![image](https://user-images.githubusercontent.com/15994713/75233140-ac079b00-57b8-11ea-91e0-e77698556181.png)

So I started to re-run with slightly large boxes {'HII_DIM':100, 'BOX_LEN':150.0} and higher cadence {'Z_HEAT_MAX': 15.0 or 20.0, 'ZPRIME_STEP_FACTOR': 1.02} and ALPHA_ESC~-0.5. It always failed without too many information reported from the MCMC.

`BrokenProcessPool exception (most likely an unrecoverable crash in C-code).       `   
          
  ` Due to the nature of this exception, it is impossible to know which of the following parameter
  vectors were responsible for the crash. Running your likelihood function with each set
  of parameters in serial may help identify the problem.`

 I've been trying with different combinations of box size, resolution and cadence as well as the starting point of ALPHA_ESC, while some MCMCs are still running, some failed and one of them reported that the crash might come from this line where we have tried too many times for the analytic curve... I'm wondering if simply increasing the allowed number of trying is enough or if there is a better way to handle it?

**Comment by steven-murray** [comment] 2020-02-25 13:14
This is definitely a bug (we should aim at never ending up with a `BrokenProcessPool` exception, especially not without due warning to the user). 

That said, I know this has been very tricky. I'm not sure how to "fix" it, but certainly once the `better-exceptions` branch has been merged, we can at least make the exit more graceful, and let the user know what's happening.

I'm sure @BradGreig has some more thoughts :-)

**Comment by qyx268** [comment] 2020-02-25 16:50
![image](https://user-images.githubusercontent.com/15994713/75267468-92854400-57f6-11ea-9442-7158130634b2.png)

Hey @BradGreig , is it normal to still have these kinks in the EoR history. I only used Park+ models. You could see (again the orange one, thick is the median and thin is the 50 random models) after xH reaches PhotonConsEnd, the eor becomes not smooth. Is it because of the extrapolation once xH<PhotonConsEnd?

**Comment by BradGreig** [comment] 2020-02-26 03:56
Hey @qyx268 can you please provide a minimum working example for me for these two cases. Basically, the exact parameters. In the absence of these, it is really difficult to be able to figure out whats going on.

I happen to have a grid of 2000 models lying around, none of which show these kink features you are finding. Thus, I need your setup and which parameters (also what branch) to try and diagnose it.

Photon non-conservation stuff should be independent of ZPRIME_STEP_FACTOR and Z_HEAT_MAX. Actually, your usage of these argument makes me wonder what branch you are on, and how recently you pulled from the master branch.

**Comment by BradGreig** [comment] 2020-02-26 05:21
I should add that for an increasing ZPRIME_STEP_FACTOR kinks in the resultant reionisation history can become more prevalent purely because you have less datapoints to construct a reionisation history. Perhaps this is the cause for the latter case. There isn't really much that can be done about that though.

**Comment by qyx268** [comment] 2020-03-03 20:11
Hi @BradGreig , I am at commit c1214fc2cddb290a91717cc5d369c059c9dea69d on master.

Here is a example where parameters are 
`user_params = {'HII_DIM':50, 'BOX_LEN':125.0}`
`cosmo_params = {'SIGMA_8': 0.8118, 'hlittle': 0.6688, 'OMm': 0.321, 'OMb':0.04952, 'POWER_INDEX':0.9626}`
`flag_options = {'USE_MASS_DEPENDENT_ZETA': True, 'INHOMO_RECO': True, 'PHOTON_CONS': True}`
`astro_params = {'F_STAR10':-1.09, 'ALPHA_STAR':0.26, 'F_ESC10':-1.10, 'ALPHA_ESC':0.16, 'M_TURN':9.46, 't_STAR':0.55}`

![image](https://user-images.githubusercontent.com/15994713/75814949-e5c93a80-5d92-11ea-8188-5c0a72cd70a0.png)


I now start to believe that I'm not using the output correctly. What I was plotting is `lightcone.global_xHI` against `lightcone.node_redshifts`. I just realized that there is more information in `lightcone.photon_nonconservation_data`. Is it true that we need to use it to calibrate the redshifts instead of directly using node_redshifts (or/and the nf)? How does the mapping work in this case? I'm not sure I understand the length of `lightcone.photon_nonconservation_data`. They don't match the length of global_xHI.

**Comment by BradGreig** [comment] 2020-03-04 05:46
Hi @qyx268, ok, I can reproduce the issue. It'll take me a bit of time to dig into whats happening and try to come up with a robust solution. I was able to reproduce it off a different branch.

No, you are using the output correct. The `lightcone.photon_nonconservation_data` is used for understanding the calibration etc.. It uses a few different pieces, hence they are of different size. Analytic come from evaluating the filling factor, calibration is running 21cmFAST with everything off to perform the mapping. And the last two pieces are for resultant delta-z given a neutral fraction (i.e. the actual calibration).

**Comment by qyx268** [comment] 2020-03-04 23:10
I now start to think it might not be related to the PHOTON_CONS feature. I've done exactly the same MCMC with PHOTON_CONS=False. We don't get the tail at low-xH and you see sudden drops when xH is relative small. 

![image](https://user-images.githubusercontent.com/15994713/75931440-44ff7b80-5e75-11ea-8376-a2ccd00d4a06.png)


I've also done the case study using the same setup but without PHOTON_CONS. You can see a sudden drop after xH reaches 0.2
![image](https://user-images.githubusercontent.com/15994713/75931518-79733780-5e75-11ea-93fd-178bfcc41d97.png)

I'm using default ZPRIME_STEP_FACTOR (1.02), I will try with an even higher cadence.

**Comment by BradGreig** [comment] 2020-03-04 23:36
Hey @qyx268, the drop is certainly a feature of the setup, not much you can do about that I don't think. However, that bump-like feature is definitely coming from the photon non-conservation side of things.

Also, have you managed to find a parameter set which fails the initial loop too many times?

**Comment by andreimesinger** [comment] 2020-03-05 00:06
thanks a lot yuxiang,

i think it would be useful to look closer in a sample model and see, for example, what is the mean number of recombinations..
 the tail comes from recombinations and maybe for some reason recombinations are being underestimated in this set up...

there seems to be another problem with this, in that the orange EOR histories seem to be too early.  i.e. the taue distributions look different for the two sets and orange seems too early.   are we sure that perhaps the likelihood is not being computed with the unnormalized EOR histories?

**Comment by BradGreig** [comment] 2020-03-05 01:42
Hi @qyx268, I dug into things a little further, and it boils down to your box size being too small (i.e. there isn't an issue with the photon non-conservation). By having subgrid recombinations, you are filtering over a 50Mpc scale within a 125 Mpc box. This is causing that sudden drop to zero which is causing that kink feature. Increasing the box size it all goes away.

As for the original problem, having models which are failing too many times in the analytic solution, I cannot investigate until I have some parameters to play with from the offending models.

**Comment by steven-murray** [comment] 2020-03-05 14:21
@BradGreig perhaps the right thing to do then is to issue a warning when the box size is this small with subgrid recombinations turned on?

**Comment by BradGreig** [comment] 2020-03-06 02:51
@steven-murray, I think you are right. Though, I think it should be a more generalised warning relating `R_BUBBLE_MAX` to the box size. I'll need to do some tests to see if there is a robust ratio that we can place a warning on. It could also be somewhat resolution dependent too (i.e. voxel size).

**Comment by steven-murray** [comment] 2020-03-06 03:08
Hmmm, fair enough.

I wonder -- could we put some rough limit warning in now, make an issue to
do a better job later, and set that for v3.1?

**Comment by BradGreig** [comment] 2020-03-06 03:30
Yeah, I was thinking of doing a rough check in the background today. This can serve as the rough limit. We can then decide at a later date if it needs to be more robust, or if the rough limit seems sufficient

**Comment by BradGreig** [comment] 2020-03-06 04:32
@steven-murray, ok, it's more trivial than I originally thought. It's actually specific to a particular filter. If `global_params.HII_FILTER == 1` then `R_BUBBLE_MAX` must be greater than or equal to 3.0. If any other filter is adopted, it doesn't matter.

This should be able to make it easy to catch from the Python end of things.

**Comment by qyx268** [comment] 2020-03-06 10:55
> Also, have you managed to find a parameter set which fails the initial loop too many times?

I think I missed this. I would try to find it now.

**Comment by steven-murray** [comment] 2020-03-06 15:38
@BradGreig so the lower limit is simple... what about the upper limit?

**Comment by qyx268** [comment] 2020-03-06 16:31
Hi @BradGreig . You are right, the box size is the reason for the sudden drop. I've tested using the same astro params but with larger box  {'HII_DIM':128, 'BOX_LEN':250.0}. Here are the results without photon con:
![image](https://user-images.githubusercontent.com/15994713/76102332-24980400-5fd0-11ea-8fc7-99e03fe02a09.png)
and with photon con:
![image](https://user-images.githubusercontent.com/15994713/76102352-2c57a880-5fd0-11ea-98cd-800eedf34cfa.png)

You see we do have smoother evolution at low xH, but still the photon con is causing this kink...

**Comment by BradGreig** [comment] 2020-03-09 01:20
Hi @qyx268, this is what I recover using the exact commit you provided [ReionisationHistory_calibrated.pdf](https://github.com/21cmfast/21cmFAST/files/4304219/ReionisationHistory_calibrated.pdf)

When running it are you sure the cache is clean? (I don't suspect this to be an issue, but I am not sure why the results are that different).  This can also be achieved by setting `regenerate = True`.

Could you also provide a figure of the nf_photoncons vs delta_z_photon_cons data that you get by returning the photon cons data. This is what I get for your parameter setup.
[ReionisationHistory_calibrationdata.pdf](https://github.com/21cmfast/21cmFAST/files/4304229/ReionisationHistory_calibrationdata.pdf). This may help diagnose if something is going wrong in the photon non-conservation correction.

**Comment by BradGreig** [comment] 2020-03-09 01:21
@steven-murray I'm not sure what you mean by upper limit. There is no need for an upper limit, just need to have a minimum box size given `R_BUBBLE_MAX`. Unless I am misinterpreting what you mean.

**Comment by qyx268** [comment] 2020-03-09 11:27
ah, this is weird... this is my calibration history, looks like there is something wrong after xH=0.4?
![image](https://user-images.githubusercontent.com/15994713/76208129-59d66900-61ff-11ea-9947-5f193f5a3e71.png)

I'm gonna rerun it with regenerate=1.

**Comment by steven-murray** [comment] 2020-03-09 17:59
@BradGreig Sorry for being unclear. I'm assuming that there is a specific input box size, and that `R_BUBBLE_MAX` is being set to some value. You're saying that if `global_params.HII_FILTER == 1`, we should be ensuring that `R_BUBBLE_MAX >= 3.0`. But if `R_BUBBLE_MAX` is too big compared to the box size, we also need to issue a warning, right? Do we have a good idea of what that maximum is for `R_BUBBLE_MAX`, given the box size?

**Comment by qyx268** [comment] 2020-03-09 19:00
I've rerun it with regenerate. It looks like what you have now @BradGreig ... 

![image](https://user-images.githubusercontent.com/15994713/76221216-096c0500-6219-11ea-8967-22afc8759192.png)


![image](https://user-images.githubusercontent.com/15994713/76221231-0e30b900-6219-11ea-8d11-5ba601f5eb06.png)

**Comment by qyx268** [comment] 2020-03-09 19:01
@BradGreig , I cannot reproduce what I had before. I assume I was reading some cached file probably...

**Comment by BradGreig** [comment] 2020-03-09 23:36
Hmm, this is somewhat concerning, that things read from cache produce such different results.

Also, these are not exactly the same, in fact they are quite different (your turnover for the calibration is at xH ~ 0.3, mine is at 0.4. Also, your blue never reaches the red, whereas the equivalent curves in mine do). Different ICs shouldn't be responsible for the differences. I'm going to try and dig into this a bit further today.

**Comment by steven-murray** [comment] 2020-03-10 13:58
@qyx268 if you do
```
import logging
logger = logging.getLogger("21cmFAST")
logger.setLevel(logging.INFO)
```
before you run your script, it should print out a bunch of info on what is being read from cache. Perhaps that might help.

It is strange indeed that you're getting very different results from a cache run compared to your current run. Perhaps the cached file is very old and had a bug in the version that produced it?

If this is the case, it is another reason to do #102

**Comment by qyx268** [comment] 2020-03-10 20:08
@BradGreig  are we using the same box setup and ZPRIME_STEP_FACTOR? mine is 
{'HII_DIM':128, 'BOX_LEN':250.0}
{'Z_HEAT_MAX': 15.0, 'ZPRIME_STEP_FACTOR': 1.02}

**Comment by qyx268** [comment] 2020-03-10 21:13
I just reran it with a bit smaller cadance 
global_params = {'Z_HEAT_MAX': 25.0, 'ZPRIME_STEP_FACTOR': 1.05}

I got even weird resutls...

![image](https://user-images.githubusercontent.com/15994713/76359936-4967e080-631c-11ea-818c-a71a02e71e9f.png)

![image](https://user-images.githubusercontent.com/15994713/76359942-4f5dc180-631c-11ea-93a3-4f353a449063.png)

**Comment by BradGreig** [comment] 2020-03-11 06:31
Hi @qyx268, yes, I am running exactly the same setup as you. I've been using the same parameters since you've provided above. I changed the cadence as you did, and I got very similar results to what I showed before (not showing any weird results). 
[ReionisationHistory_calibrated.pdf](https://github.com/21cmfast/21cmFAST/files/4316378/ReionisationHistory_calibrated.pdf)
[ReionisationHistory_calibrationdata.pdf](https://github.com/21cmfast/21cmFAST/files/4316379/ReionisationHistory_calibrationdata.pdf)

Have you emptied the cache to make sure you aren't reading in anything from file (or checked the log as @steven-murray suggested).

I've ran two separate branches on my laptop and one on ozstar and all return the same results. Are you sure you haven't made a change somewhere?

**Comment by BradGreig** [comment] 2020-03-11 06:38
@steven-murray, sorry, missed your comment again. I guess in general `R_BUBBLE_MAX` should be at the size of or less than `BOX_LEN`, however this is dependent on the chosen filter. I guess you can through up a warning if `R_BUBBLE_MAX >= BOX_LEN`. And then if `global_params.HII_FILTER == 1` is set (which is the default) then it'll also through up the secondary warning that `BOX_LEN >= 3. * R_BUBBLE_MAX `. I just realised that what I typed previously might have been causing the confusion! Does this now make sense?

**Comment by qyx268** [comment] 2020-03-11 18:37
I checked before these tests. My master should be the same as from the github...

So I've tried something more. I ran the simulation, got a result like this:
![image](https://user-images.githubusercontent.com/15994713/76450603-5d6c1a80-63ce-11ea-9c46-576264f19b95.png)
Then, I reran it with regenerate=True, I got this:
![image](https://user-images.githubusercontent.com/15994713/76450640-6ceb6380-63ce-11ea-960a-15693e7874a6.png)
Then, I reran it with regenerate=False, I got INFO from the logger saying that I'm using the perturb_field and ionized boxes. However, I think it still reran ComputeIonizedBox and the result looks like this:
![image](https://user-images.githubusercontent.com/15994713/76450708-88566e80-63ce-11ea-9063-a8fa38592a0f.png)

You see that all of these 3 results look different (they all have the same nf_photoncons-delta_z_photon_cons relation as shown before). This made me wonder if it's related to the seed, which I didn't specify in any of these runs. I'm wondering if you can reproduce the second result with seed=313065944211?

**Comment by BradGreig** [comment] 2020-03-11 23:39
@qyx268, here is my curve with the seed you suggest. [ReionisationHistory_calibrated.pdf](https://github.com/21cmfast/21cmFAST/files/4321511/ReionisationHistory_calibrated.pdf)

The black curve does seem to be consistent with the blue curve (maybe?). What is the red dashed curve in your figure? My blue dashed curve is the "calibration" data and the red dashed curve is the "analytic" curve. Can you please plot both of those as this will help me understand what is happening.

If your red dashed curve is the "calibration" data what concerns me is that its different to mine. Hence, looking at the analytic curve can at least let me see if something strange is going on.

**Comment by qyx268** [comment] 2020-03-12 21:59
sorry, I should have been more clear. I now believe that previously, 
your black and my blue are the same which are the EoR history when PHOTON_CONS = True (i.e. global_xHI v.s. node_redshifts)
but your blue is not my red. I think your blue is nf_calibration v.s. z_calibration while my red is still the EoR history (i.e. global_xHI v.s. node_redshifts) but with PHOTON_CONS = False. 

Below is my result using your colours... So now you see the blue, black and red are the same as yours with now the green (previously the red) being the EoR history re-runed with PHOTON_CONS = False. The difference we saw is just due to recombination I think...
![image](https://user-images.githubusercontent.com/15994713/76569536-a2b64800-64b3-11ea-8596-f4490e89065f.png)

I think there is no problem excepted for the small box (which is also not a problem, just a misuse imo). Sorry for taking us too long... Also, the issues of "photon con failed too many times" never happened again. I guess I was truly using some cached file that might give an unmatched eor history and let the mapping fail too many times. This might be related to what jaehong found in #109? 

I will keep an eye on this and reopen this issue if I encounter it again. Please close this issue if you agree...

**Comment by qyx268** [comment] 2020-03-12 22:32
Just in case I wasn't using the latest master, I redid the previous plot on my laptop (previously I did it on nefertem...). I cleaned the folder and made sure there is no cache. I am at the latest master of 0c7b51aa0e08d60c771999996d034f041e256307

The result (black) is slightly different while the others remain unchanged. 
![image](https://user-images.githubusercontent.com/15994713/76571909-f11a1580-64b8-11ea-8267-047840d8dd84.png)
This is because my delta_z_photon_cons v.s. nf_photoncons looks weird...
![image](https://user-images.githubusercontent.com/15994713/76572005-24f53b00-64b9-11ea-9d9c-2214c252c3a3.png)

@BradGreig  Can you double-check if this is also happening to you? I'm attaching my notebook here:
https://www.dropbox.com/s/8hj7kf2q3i72lg4/testing_PHOTON_CONS.ipynb?dl=0

**Comment by BradGreig** [comment] 2020-03-12 23:41
Hi @qyx268, ok, that makes a lot more sense. I should have clarified what the curve meant, rather than just assuming it was what I was plotting. To me, this all looks to be functioning as expected.

I see the same behaviour as you are for delta z vs xHI, however this actually makes sense. What the xHI corresponds to here is from the calibration curve (i.e. blue dashed curve). When the blue curve is xHI ~ 0.55 this corresponds to the red curve crossing xH ~ 0.3. The correction switches at xHI ~ 0.3 (to remove kinks etc.) to a different extrapolation. Thus, the curve shown in delta z vs xHI is no longer used beyond this xHI.

Its all a bit confusing, but you can see that the shape of your green and the black are essentially identical. Which is effectively what you want, that is pulling back the history.

I'm going to close this, as I believe everything is behaving as expected and given there is #109.

**Closed by BradGreig** 2020-03-12 23:41 UTC
Labels: C-backend, bug, question
