### ISSUE TITLE
ring sturcture shows up in large-volume simulations

### ISSUE THREAD

**Issue by qyx268** [21cmfast/21cmFAST#194] opened 2020-12-03 19:02 UTC
**Describe the bug:**

When we have large-volume simulations, we get ring structures on scales of Gpc, in particularly in the photoionization rate box. I'm thinking if this is due to the 

![image](https://user-images.githubusercontent.com/15994713/101073153-50680a80-359f-11eb-83fe-9e230b430d92.png)

**To Reproduce:**
You just need a large-volume simulation... You can reproduce with this script. 
[run.txt](https://github.com/21cmfast/21cmFAST/files/5638255/run.txt)

**Expected behavior:**

**Details:**
 - OS: Linux nefertem.sns.it 2.6.32-504.hz100.el6.x86_64 #1 SMP Fri Oct 31 20:08:27 CDT 2014 x86_64 x86_64 x86_64 GNU/Linux
 - Python Version: 3.6.5

**Additional context**

Has anyone had large-volume simulations performed with the old 21cmfast or 21CMMC driver? It will be helpful to see if this is a new thing in v3 or it has always been there but missed.

**Comment by qyx268** [comment] 2020-12-03 22:54
@andreimesinger  any further thoughts here? apart from R_BUBBLE_MAX, which is set to 50 atm when INHOMO_RECO is on, I don't even know where to begin... I'm thinking of setting it to 200 and see if the rings disappear or look differently...

**Comment by andreimesinger** [comment] 2020-12-03 22:59
this one is very strange…  i wouldn’t know where to begin..  your test sounds good, though i cannot see how that could be the issue…  it looks like some sampling problem.

i would need to look at the code to be more useful here. maybe monday i can see, if it hasn’t been fixed by then

**Comment by BradGreig** [comment] 2020-12-04 05:36
Hmm, this is going to be problematic to discover given the size of the simulation. I've had a brief mess around but haven't come up with anything yet. I've tried a L = 500 Mpc, HII_DIM = 400 box (evolving the density linearly to try and minimise compute time) but that didn't show up anything.

I have seen ring structure before, however, that was around each source not centred on one location like this is. Switching the HII_FILTER from k-space to real-space resolved that, however, I don't think it'll help in this instance.

If you have stored all the intermediate boxes maybe look at a single co-eval box and see if its visible in any slice. Maybe you'll be able to identify the first redshift where it appears and then be able to only run a single co-eval box to establish what is going on.

**Comment by steven-murray** [comment] 2020-12-04 15:22
@qyx268 is this one run the only time you've seen it occur? Or does it occur in every run?

**Comment by qyx268** [comment] 2020-12-04 17:16
@steven-murray  no, this is the only large-volume run i have ever had... 

@BradGreig yes, i checked the co-eval boxes. they are visible. 
![image](https://user-images.githubusercontent.com/15994713/101193182-7ef7eb00-365c-11eb-915e-899424795730.png)


I think they are there even at higher redshifts. But they dont show up, because Gamma is low at high-z. But if you flip between these redshifts, you can sort of tell they are present at high z too....
![image](https://user-images.githubusercontent.com/15994713/101193253-9931c900-365c-11eb-993c-c2a85247f5e7.png)

![image](https://user-images.githubusercontent.com/15994713/101193273-a0f16d80-365c-11eb-813d-d1fde938d024.png)

**Comment by andreimesinger** [comment] 2020-12-04 17:41
i don’t  see it in high redshifts.  only post eor where we don’t trust the calculation so much.  we should look into this, but the velocity bug is more urgent. imo

**Comment by steven-murray** [comment] 2020-12-07 17:25
@qyx268 Might it be a good idea to run a few with different options switched on and off to hone in on the likely cause?

**Comment by qyx268** [comment] 2020-12-07 17:27
yeah, the thing is we don't really know what is likely causing this... The only thing I am betting on is actually in GlobalParams. If this doesn't give me any hint, I will do a grid search I guess...

**Comment by steven-murray** [comment] 2020-12-07 17:37
yeah, that could be an onerous process. Is it just in the photoionization rate? Or are there other quantities that show it?

**Comment by qyx268** [comment] 2020-12-07 18:05
looks like it's only in Gamma. This plot shows from left to right, Gamma, z_re, kinetic T, log dNrec, log Fcoll.  

![image](https://user-images.githubusercontent.com/15994713/101387698-1bb9c300-38bf-11eb-9533-6a2f023e51c6.png)

**Comment by andreimesinger** [comment] 2020-12-07 18:09
what was the max mean free path used here?  there is a clear imprint of the Rmax here, which comes from using the code beyond the regime in which it was intended…

does the ring like thing change if you pick different slices?

**Comment by qyx268** [comment] 2020-12-07 18:17
it changes 
![image](https://user-images.githubusercontent.com/15994713/101388858-d0081900-38c0-11eb-9bf7-bc8705325019.png)

Rmax = 50 when inhomo_reco is enabled

**Comment by andreimesinger** [comment] 2020-12-07 18:19
hmm…  the fact that the center is always at the same place is really strange..

**Comment by qyx268** [comment] 2020-12-07 18:20
i assume that's the density peak

**Comment by andreimesinger** [comment] 2020-12-07 18:21
yeah, but if you go far away with your slices you will lose that peak..  did you plot distant slices or neighboring ones?

**Comment by qyx268** [comment] 2020-12-07 18:22
Distant..

**Comment by steven-murray** [comment] 2020-12-07 20:19
This is all weird. I can definitely see the ring structure (less pronounced) in the other fields.

**Comment by BradGreig** [comment] 2020-12-08 00:27
@qyx268 it might be worth sorting the density field to see the high density peaks. To see if one or a few high values are near the central region of this structure.

In terms of debugging, it might be worth extracting a smaller cube centred around this area and running the code on the sub-volume. This will likely require hacking the code, but might assist debugging it faster by significantly reducing the simulation volume.

I still recommend switching the HII_FILTER to see if this goes away.

**Comment by qyx268** [comment] 2020-12-08 14:18
Those are good suggestions. I will take a look at the HII_FILTER. Here are results with Rmax=200...
![image](https://user-images.githubusercontent.com/15994713/101494197-4d866480-3967-11eb-88f6-e42631eb50f2.png)

![image](https://user-images.githubusercontent.com/15994713/101494393-91796980-3967-11eb-99d7-85bbdbf6c3b0.png)

**Comment by qyx268** [comment] 2020-12-08 14:24
```
                            // check if fully ionized!
                            if ( (f_coll * ION_EFF_FACTOR + f_coll_MINI * ION_EFF_FACTOR_MINI> (1. - xHII_from_xrays)*(1.0+rec)) ){ //IONIZED!!
                                // if this is the first crossing of the ionization barrier for this cell (largest R), record the gamma
                                // this assumes photon-starved growth of HII regions...  breaks down post EoR
                                if (flag_options->INHOMO_RECO && (box->xH_box[HII_R_INDEX(x,y,z)] > FRACT_FLOAT_ERR) ){
                                    box->Gamma12_box[HII_R_INDEX(x,y,z)] = Gamma_R_prefactor * f_coll + Gamma_R_prefactor_MINI * f_coll_MINI;
                                }

                                // keep track of the first time this cell is ionized (earliest time)
                                if (previous_ionize_box->z_re_box[HII_R_INDEX(x,y,z)] < 0){
                                    box->z_re_box[HII_R_INDEX(x,y,z)] = redshift;
                                } else{
                                    box->z_re_box[HII_R_INDEX(x,y,z)] = previous_ionize_box->z_re_box[HII_R_INDEX(x,y,z)];
                                }

                                // FLAG CELL(S) AS IONIZED
                                if (global_params.FIND_BUBBLE_ALGORITHM == 2) // center method
                                    box->xH_box[HII_R_INDEX(x,y,z)] = 0;
                                if (global_params.FIND_BUBBLE_ALGORITHM == 1) // sphere method
                                    update_in_sphere(box->xH_box, user_params->HII_DIM, R/(user_params->BOX_LEN), \
                                                     x/(user_params->HII_DIM+0.0), y/(user_params->HII_DIM+0.0), z/(user_params->HII_DIM+0.0));
                            } // end ionized
```

This is how we assign values to Gamma12_box. I think at lower redshifts, the first `if` is True even at the largest filtering radius. Therefore, the ring structure depends on Rmax.

**Comment by andreimesinger** [comment] 2020-12-08 14:25
i think you need to extend your color map for gamma…  but you still get the “feature” that there is a “center” to the maps…  i don’t know where this would come from…  i think the code needs to be checked; doing these diagnostics is pretty random/inefficient without understanding what the code is doing…  i can take a look in a bit

**Comment by qyx268** [comment] 2020-12-08 14:26
the color bar is extended. otherwise, this is what u will see 
![image](https://user-images.githubusercontent.com/15994713/101496155-b40c8200-3969-11eb-9072-1fbb72704f0f.png)

**Comment by qyx268** [comment] 2020-12-08 14:30
I'm not sure I follow the point about there is a center. We do filtering in 3D. The ring in the 2D maps are shells in 3D. It just says there is a density peak in 3D. What's wrong with this?

e.g. this is what happens if I slide on different plane 

![image](https://user-images.githubusercontent.com/15994713/101496644-4b71d500-396a-11eb-83c7-e03e6d23674e.png)

![image](https://user-images.githubusercontent.com/15994713/101496659-4f9df280-396a-11eb-9949-622dbd8b4a24.png)

**Comment by andreimesinger** [comment] 2020-12-08 14:31
btw, the Rmax is necessary in this calculation post EoR…  because we originally were not intending to use the code post EoR, i took the value of 50 Mpc as a reasonable max at z~5.5-6.  but post overlap, the code doesn’t make sense without having an Rmax as either a free parameter, or taking an observational estimate of mfp redshift evolution

**Comment by andreimesinger** [comment] 2020-12-08 14:34
why is there a center, even if does correspond to a density peak?  if you filter the density field with some R_filter = 50Mpc, you just get a smoothed density field; you don’t get one sphere..

**Comment by qyx268** [comment] 2020-12-08 14:40
i'm not saying this is correct. I think this might be due to the filtering as brad said.

**Comment by qyx268** [comment] 2020-12-08 14:41
looks up, some how, we update Gamma_12 using the sphere method... but i cant find it easily in the code

**Comment by andreimesinger** [comment] 2020-12-08 14:45
yes, it is looks like it is something in the sampling, like that only some cells end up getting sampled or updated

**Comment by qyx268** [comment] 2020-12-08 14:46
speaking of using Rmax in post EoR, if this is a MFP argument, shouldnt Gamma be more or less a uniform background when the bubble overlapped?

**Comment by andreimesinger** [comment] 2020-12-08 14:51
exactly…  it should be something very similar to filtering the density field on the scale of the mfp (with some normalization of course)

**Comment by andreimesinger** [comment] 2020-12-09 15:53
looking at the code, i cannot see anything obviously wrong (at least not in my OC version).  the only thing that comes to mind is that the fcoll interpolation tables might be inaccurate in some extreme regime, maybe producing non continuous outputs…  because from the image, it looks like the ring is centered around a void and the rings come from concentric filterings around this void.

i think one needs to print out some same fcoll and gamma outputs from this if statement: 

	      // if this is the first crossing of the ionization barrier for this cell (largest R), record the gamma
	      // this assumes photon-starved growth of HII regions...  breaks down post EoR
	      if (INHOMO_RECO && (xH[HII_R_INDEX(x, y, z)] > FRACT_FLOAT_ERR) ){
		Gamma12[HII_R_INDEX(x, y, z)] = Gamma_R;


note the warning message i had put here when i wrote this…   in the medium-long term, we should improve the physics here, so as to enable it to work better post EoR… 

-a

**Comment by qyx268** [comment] 2020-12-16 15:53
still haven't had a change to look into this. But the run @BradGreig  suggested with HII_FILTER=0 has finished. Just wanted to post the result here if anyone has some insights... 

![image](https://user-images.githubusercontent.com/15994713/102371851-ec8e0a80-3fbe-11eb-9bec-eda74460d236.png)
This can be compared to 
https://github.com/21cmfast/21cmFAST/issues/194#issue-756476531

![image](https://user-images.githubusercontent.com/15994713/102372102-295a0180-3fbf-11eb-8cda-6952ac0cecf8.png)
compared to 
https://github.com/21cmfast/21cmFAST/issues/194#issuecomment-740084560

![image](https://user-images.githubusercontent.com/15994713/102371886-f57edc00-3fbe-11eb-8fcd-591d43b8f49a.png)
compared to 
https://github.com/21cmfast/21cmFAST/issues/194#issuecomment-740091432

**Comment by steven-murray** [comment] 2020-12-16 16:56
What is that weird cross structure?!

**Comment by andreimesinger** [comment] 2020-12-16 17:01
looks like it is aliasing around the same point (underdensity probably) that was causing the trouble with the other filter…  i still suspect some of the fcoll interpolation tables are giving outlying results at these redshifts, driving these weird things

**Comment by andreimesinger** [comment] 2020-12-16 17:03
the cross is the center of the previous “wheel”…  this is why i think it is a “hot pixel” or something

**Comment by steven-murray** [comment] 2020-12-16 17:09
I agree, there's definitely something numerically strange going on with
that pixel/small region.

**Comment by qyx268** [comment] 2021-01-24 22:59
some follow up on this... in case people have any further suggestions...

So this appears to exist only in high-res, >=1Gpc boxes.

e.g. this is Gamma slices at low-z in a 800Mpc simulation:
![image](https://user-images.githubusercontent.com/15994713/105646298-7626d700-5e9f-11eb-8ce9-bb4d56cbc9c0.png)

this is Gamma slices at low-z in a 1Gpc but low-res simulation:
![image](https://user-images.githubusercontent.com/15994713/105646328-abcbc000-5e9f-11eb-9fe4-4498df697c12.png)

The most important thing is that this also appears to be affecting the global eor history
![image](https://user-images.githubusercontent.com/15994713/105646315-8fc81e80-5e9f-11eb-970e-6095a84210ce.png)

I've also check simulation outputs from v2. Unless the seed is playing a role here, this bug only exists in v3...
![image](https://user-images.githubusercontent.com/15994713/105646410-1a108280-5ea0-11eb-9d03-4987ed758ec0.png)
![image](https://user-images.githubusercontent.com/15994713/105646404-13820b00-5ea0-11eb-9316-7541d9949249.png)
(p.s. the 1125Mpc run used a large Mturn)

**Comment by BradGreig** [comment] 2021-01-29 01:51
Hey @qyx268, can you determine the min/max density for each filtering radius for any co-eval box that contains the ring-like structure. You should also consider outputting the cell location, to see if it is located near the centre of the ring (you roughly know the centre in the x-y plane). Or, extract a cuboid around roughly the centre of the ring (knowing the x-y coordinates, and look through the z direction) to search for extreme densities etc.

If you can determine this, then you might be able to track through this (or a few cells) and output various quantities. This way you might be able to establish what is going on, and where.

It might also be worth trying the exact same setup you have used except setting `USE_MASS_DEPENDENT_ZETA = False`. Setting this to False will remove the need for any interpolation tables, and use the error function for f_coll. This would highlight if any of the interpolation tables (for mass dependent zeta) are having issues.

**Comment by qyx268** [comment] 2021-01-29 01:59
Thanks for these suggestions. I did some of then already. e.g. the ring center doesn't always match the location of the lowest density... also checked the min/max density before filtering (i.e. Perturb), 800Mpc which has no ring structures can span a larger density range than the 1Gpc run... I'll try to check the smoothed density, though I doubt exceeding the density range in the interpolation table is the case though... 

I'm trying some switches at the moment, I will try USE_MASS_DEPENDENT_ZETA later. The RAM on nefertem is pretty full atm..

**Comment by BradGreig** [comment] 2021-02-05 06:42
Hey @qyx268, just thinking about this some more. It might be worth outputting delta_R (smoothed) and f_coll for all smoothing radii.

Looking at your `HII_FILTER = 0` case, you can see the aliasing in the xHI field. Thus, the source of this can only be coming from f_coll or delta_R. I suspect this aliasing will then be prevalent in either f_coll or delta_R (most likely f_coll). Where it appears (i.e. which R) would then allow you to narrow down the source of the problem.

**Comment by qyx268** [comment] 2021-02-05 07:14
I did show f_coll at the last filtering radius. I'll look into this more.

> looks like it's only in Gamma. This plot shows from left to right, Gamma, z_re, kinetic T, log dNrec, log Fcoll.
> 
> ![image](https://user-images.githubusercontent.com/15994713/101387698-1bb9c300-38bf-11eb-9533-6a2f023e51c6.png)

So far, I can confirm that with USE_MASS_DEPENDENT_ZETA off, we still see this.
![image](https://user-images.githubusercontent.com/15994713/107001033-34dcd400-6789-11eb-9a35-5ec0bbb4976d.png)

I'm still not convinced this is due to existing codes that we just copy from v2. I wanted to see the result from PERTURB_ON_HIGH_RES=False

**Comment by BradGreig** [comment] 2021-02-05 07:37
Interesting, the fact it appears in the `USE_MASS_DEPENDENT_ZETA = False` case means it is highly likely linked to the density field. Maybe try outputting the smoothed density field (see if it suddenly appears for the certain R).

Also, xHI looks very weird above. Maybe an issue with the lightcone generation?

**Comment by qyx268** [comment] 2021-02-05 07:47
yeah, that's a good idea. I will check them.

the lightcone looks weird because I only have 7 coevolve boxes.

```
p21c.global_params.Z_HEAT_MAX = 15.0
p21c.global_params.ZPRIME_STEP_FACTOR = 1.2
redshift = 4.9
```

**Comment by qyx268** [comment] 2021-02-08 11:14
some updates in case people have suggestions.

1. with USE_MASS_DEPENDENT_ZETA = False, USE_INTERPOLATION_TABLES=False, PERTURB_ON_HIGH_RES=False, USE_FFTW_WISDOM=False, the rings are still there... This does help shorten `IonisationBox.c` a lot. However, I still cant see anything wrong...
2. There is a small difference between v2 and v3 -- the size/structure of `Fcoll`, it is `HII_TOT_FFT_NUM_PIXELS` and using `HII_R_FFT_INDEX` in v2 while in v3, it's `HII_TOT_NUM_PIXELS` and `HII_R_INDEX`. However, this doesn't matter and having Fcoll in `HII_R_INDEX` system is actually better since then Fcoll can be reshaped into (HII_DIM,HII_DIM,HII_DIM).
3. Fcoll at different filtering radius looks okay... 
![image](https://user-images.githubusercontent.com/15994713/107210966-2ef32700-6a05-11eb-89be-e8370d8429e2.png)
4. Previously, I added a calculation of MFP because of the forest project. It's in the same `if` statement where we assign Gamma12
```
if (flag_options->INHOMO_RECO && (box->xH_box[HII_R_INDEX(x,y,z)] > FRACT_FLOAT_ERR) ){
                                    box->Gamma12_box[HII_R_INDEX(x,y,z)] = Gamma_R_prefactor * f_coll;
                                    box->MFP_box[HII_R_INDEX(x,y,z)] = R;
                                }
```
Then I found the ring structures also exist in MFP.
![image](https://user-images.githubusercontent.com/15994713/107211164-74175900-6a05-11eb-968d-3ce16e63ad70.png)
(left to right: Gamma12_box, z_re_box, temp_kinetic_all_gas , dNrec_box, Fcoll[lagest R], and MFP_box).

I'm doing a run where rec is fixed at zero to see if something wrong in rec (i.e. N_rec_filtered)... which i really doubt though considering dNrec_box looks fine. let's see...

**Comment by qyx268** [comment] 2021-02-09 00:10
fixing rec=0 does remove the rings...

**Comment by qyx268** [comment] 2021-02-09 00:14
![image](https://user-images.githubusercontent.com/15994713/107297645-12da9e80-6a74-11eb-9b90-d4d47bef978a.png)

**Comment by BradGreig** [comment] 2021-02-09 02:02
Hmmm, but I don't think it is the recombinations that is the actual problem. The structure might be appearing there, but the source must be elsewhere. For example, if it was in the recombinations, then it should have also appeared in the `USE_MASS_DEPENDENT_ZETA = False` case.

Can you try outputting the same result you have above (for point 4., with Gamma and MFP), except changing `FRACT_FLOAT_ERR` just in that specific line of code where Gamma and MFP are generated. Say trying 1e-10 and 1e-4 (default value is 1e-7). I'm wondering if the ionisation critera just happens to be right on the numerical accuracy threshold, and thus the ring structure might be caused by this criteria being met for different radii.

I think the ring structure has to be sourced directly by the ionisation criteria. It might also be worth plotting the ionisation critera as a function of smoothing radius. I would plot both `f_coll * ION_EFF_FACTOR` and `(1. - xHII_from_xrays)*(1.0+rec)` as a function of smoothing radii and also a binary map of when `f_coll * ION_EFF_FACTOR > (1. - xHII_from_xrays)*(1.0+rec)` for each smoothing radii.

I think you are making great progress in isolating this issue.

**Comment by qyx268** [comment] 2021-02-09 02:17
It did appear in `USE_MASS_DEPENDENT_ZETA = False`. In fact, the recent tests were all done with `USE_MASS_DEPENDENT_ZETA = False`.

The problem seems indeed in N_rec_filtered, I found dNrec_box can be negative (in both the 1Gpc boxes and also the smaller boxes where rings dont appear). In case where rings appear, it has one cell with dNrec_box=106870880000 and xH=1. 

I'm gonna go get lunch, a quick thought is that this might be caused by not initializing previous_ionize_box->dNrec_box when `USE_MINI_HALOS=False`... However, presumably, this is not the reason here since for the first redshift
`(box->mean_f_coll * ION_EFF_FACTOR + box->mean_f_coll_MINI * ION_EFF_FACTOR_MINI< global_params.HII_ROUND_ERR)` is likely true, and then in the next snapshot, previous_ionize_box->dNrec_box will be initialized to 0 in the python part... But let's see...

I was also thinking about `FRACT_FLOAT_ERR`. I will test it after finding out why dNrec_box can be negative and >1e10...

**Comment by BradGreig** [comment] 2021-02-09 02:28
Ah oops, I misread your earlier message about `USE_MASS_DEPENDENT_ZETA = False`.

Interesting, this single large value cell for dNrec_box is likely the problem. Unfortunately you'll need to track that specific cell all the way through to find out what causes it (if that is even trivial, I don't envy that task!). It is probably occurring when dNrec is calculated (outside of the R loop, near the end of IonisationBox). I wonder if it is stepping out of the interpolation table range for some specific value.

**Comment by andreimesinger** [comment] 2021-02-09 10:18
great job isolating this!

**Comment by qyx268** [comment] 2021-02-09 11:14
fixed...  and you guys won't believe what the problem is.

`ZSTEP = prev_redshift - redshift;` this line is wrong for the first snapshot where we set `prev_redshift=0`... It is usually fine for cosmic dawn simulations where we start from higher redshifts and reionization doesn't start in the first snapshot. In this case, `ZSTEP` is not used to calculate `Nrec`. However, for these EoR simulations where I start from z=15... we will have negative `ZSTEP` for the first redshift. This gives those negative `Nrec` which propagates towards low-z and results in the anomaly (and possibly the ring structure).

![image](https://user-images.githubusercontent.com/15994713/107351582-11889080-6acb-11eb-8adc-ee7241c9920e.png)

For v2, this is not an issue because `drive_logZscroll_Ts` always passes a previous redshift to `find_HII_bubbles`...

To fix it, I will set `ZSTEP=0.2` when `prev_redshift<0` (i.e. first snapshot)... I tested using `USE_MASS_DEPENDENT_ZETA = False, USE_INTERPOLATION_TABLES=False, PERTURB_ON_HIGH_RES=False, USE_FFTW_WISDOM=False` and it worked. I will test with these flags on and with higher cadence.

**Comment by andreimesinger** [comment] 2021-02-09 11:24
👌💪

**Comment by steven-murray** [comment] 2021-02-09 20:05
Nice!

**Comment by BradGreig** [comment] 2021-02-10 01:02
Great work @qyx268!

**Comment by qyx268** [comment] 2021-02-20 12:46
the results look fine now. For the record, here are the updated LCs and Slides at z=4.9
![image](https://user-images.githubusercontent.com/15994713/108595778-bb262680-73d5-11eb-912a-e37e39694aef.png)

![image](https://user-images.githubusercontent.com/15994713/108595785-c2e5cb00-73d5-11eb-91bc-8f814689fcc3.png)

**Comment by andreimesinger** [comment] 2021-02-20 12:50
awesome!  i never get tired of looking at these plots  the large density field is especially gorgeous!

**Comment by qyx268** [comment] 2021-02-20 13:06
![Screenshot from 2021-02-21 00-03-22](https://user-images.githubusercontent.com/15994713/108596323-67690c80-73d8-11eb-9fea-33daab7a44cc.png)

probably need the higher-res run for my new screen... then I might be willing to give up the fossa :)

**Closed** 2021-02-20 19:11 UTC
Labels: status: requires discussion, type: bug
