### ISSUE TITLE
Can anyone reproduce this FFTW bug?

### ISSUE THREAD

**Issue by qyx268** [21cmfast/21cmFAST#179] opened 2020-10-13 19:48 UTC
**Describe what you would like to do**
minimum steps to reproduce this bug:
`python -c "import py21cmfast as p21c; p21c.construct_fftw_wisdoms(user_params={'USE_FFTW_WISDOM': True, 'HII_DIM':25})"`

You will find no wisdom outputs in the current directory. However, this only happens on `thanatos` and I cannot reproduce this bug on other machines. Can somebody else try on their machine? @dprelogo, it will be great if you can confirm this is also happening to you on `thanatos`. So we will know if this is just because of my environment or it's the machine...

Python 3.6.5
FFTW 3.3.8

**What I've tried**
I managed to narrow down the error to `fftwf_export_wisdom_to_filename` in `GenerateICs.c`, which return a status of 0 (failed). However, `fftwf-wisdom -o ~/wisdomf rof25 rob25` does show an output.

**Other context**

This might be related to #134 as I didn't get any information from `run_lightcone` apart from ERROR saying no wisdom files can be found...

**Comment by steven-murray** [comment] 2020-10-13 20:57
When running that command both on my own machine, and on a cluster here, I
do not get any output files in my current directory. That is on Arch Linux,
and Ubuntu.

**Comment by dprelogo** [comment] 2020-10-14 09:08
I'm confirming that there's no output on `thanatos`.
Python 3.8.1
FFTW 3.3.8

**Comment by BradGreig** [comment] 2020-10-15 01:20
I cannot reproduce this on any machine I have access too. This will make if difficult for me to try and debug...

Is someone else willing to try and figure this one out?

**Comment by qyx268** [comment] 2020-10-15 07:32
@BradGreig  Just wanted to double check. Do you mean you do see wisdom outputs in the current directory when you say you cannot reproduce this? 

I will look into this in the next couple of days.

**Comment by BradGreig** [comment] 2020-10-15 07:41
@qyx268, yes, when following your instructions, I am left with several output files in the directory (clean to begin with).

Unfortunately, I do not have access to thanatos to test this myself. 

One quick thing worth checking. Does it create the wisdoms if you have a clean directory and just call `initial_conditions`? That is bypass your direct call to `construct_fftw_wisdoms` and leave it to be done internally by `initial_conditions`. I can't see why, but a good sanity check.

**Comment by qyx268** [comment] 2020-10-24 17:07
I still cannot figure this out. I'm postponing this issue to later times. I just wanted to summarize what I did. I tried the followings:
1. manually create the file with fopen and write wisdom using `fftw_export_wisdom_to_file`. Nothing appears in the file
2. add `LOG_DEBUG("%s", fftw_export_wisdom_to_string)`. the log shows `(null)`.
3. export the wisdom file using the real data -- do `fftw_export_wisdom_to_file`at `LOG_WARNING("Cannot locate FFTW Wisdom: %s file not found",wisdom_filename)`. still no output...

**Comment by qyx268** [comment] 2020-10-24 17:08
one thing that might be related 
https://stackoverflow.com/questions/14941342/wisdom-in-fftw-doesnt-import-export

**Comment by BradGreig** [comment] 2020-10-26 01:21
Yeah, I too saw this, but it never got resolved.

Have you tried creating the wisdoms on a separate machine and then copying them over and trying to read from them?

To me, it sounds like there must be a linking or installation error under certain combinations of OS. There must be something missing. If copying over known working wisdoms, and the code still fails to read those in, then that would solidify the thinking of it being some weird linking/installation issue. Resolving this though may be complicated...

**Comment by qyx268** [comment] 2020-10-28 19:06
That's a very good suggestion. Apparently, `fftwf_import_wisdom_from_filename` also failed even with exsting wisdom files copied from another machine. 

I also think this is more like an OS issue rather than a bug in 21cmFAST. But I'm surprised at how common it is with the new code considering I've never noticed it before with the 21CMMC driver (perhaps it's also because the driver won't crash if no wisdom files have been produced)... I just double checked, it is the same with the driver that I cannot produce wisdom files on thanatos but I can do it on the other two machines. is it the same for you? @BradGreig . Actually, I'm having this deja vu that we had this conversation before... 

Anyhow, perhaps we should keep this issue open and modify the log to be something like
`Cannot locate FFTW Wisdom: %s file not found. There could be issues in your FFT library. Please set USE_FFTW_WISDOM=0`

**Comment by BradGreig** [comment] 2020-10-30 01:47
Yeah, I would vote for keeping it open for now. As a reminder of it being an open issue. Are you installing a local (user) copy of FFTW or is it a system wide FFTW on Thanatos? I'm wondering if it might be worth cycling through some major versions to see if that can isolate the problem. Wondering too if it would be worth contacting the FFTW developers.

In the meantime, I think the warning makes sense. Though, it would only be thrown up when trying to create wisdoms and it fails to write anything. Don't want this message to occur when trying to open a wisdom in the case the user never created them. If that makes sense

**Comment by steven-murray** [comment] 2020-12-30 00:05
This is now breaking tests both on my machine and on Github Actions (which runs ubuntu and macos). Not sure why it started happening?! Is there a good workaround or do we really just need to fix it?

**Comment by steven-murray** [comment] 2020-12-30 23:51
I've looked a bit more into this. Given the following very much reduced version of `CreateFFTWWisdoms`:

```c
int CreateFFTWWisdoms(struct UserParams *user_params, struct CosmoParams *cosmo_params) {
    int status;
    char *wisdom_string;


    fftwf_plan plan;
    char wisdom_filename[500];

    int i,j,k;
     int nthreads = 1;
     int dim = 75;

    omp_set_num_threads(1);
    fftwf_init_threads();
    fftwf_plan_with_nthreads(1);
    fftwf_cleanup_threads();

    // allocate array for the k-space and real-space boxes
     fftwf_complex *HIRES_box = (fftwf_complex *) fftwf_malloc(sizeof(fftwf_complex)*dim*dim*(dim/2+1));



     sprintf(wisdom_filename,"real_to_complex_DIM%d_NTHREADS%d.fftwf_wisdom", dim, nthreads);

      // Going to need to construct an FFTW_Wisdom for this box
      plan = fftwf_plan_dft_r2c_3d(dim,dim,dim,
                       (float *)HIRES_box, (fftwf_complex *)HIRES_box, FFTW_PATIENT);
      fftwf_print_plan(plan);
      printf("Made a plan!\n");
      fftwf_execute(plan);
      wisdom_string = fftwf_export_wisdom_to_string();
      printf("got some wisdom...\n");
      if (wisdom_string != NULL) {
        printf("Accumulated wisdom: %s\n",wisdom_string);
      }

      // Store the wisdom for later use
      fftwf_export_wisdom_to_filename(wisdom_filename);
      fftwf_destroy_plan(plan);
}
```

You'd expect it to print out the wisdom, but it doesn't. However, if I just take this function, whack it into a standalone C file, rename the function `main` and compile/run it, I do get the wisdom to print out.

Either my 21cmFAST library is using a different version of FFTW than my system one (I don't think so, and I can't figure out how to check), or there's something up with running this from a Python instance. Will keep digging....

**Comment by qyx268** [comment] 2021-01-03 11:11
I can confirm that your script does print the plan when it's a standalone C file. 

A quick workaround is just not using wisdom files if they are not created, which however, is not ideal... 

I also managed to make `python -c "import py21cmfast as p21c; p21c.construct_fftw_wisdoms(user_params={'USE_FFTW_WISDOM': True, 'HII_DIM':25})"` work (i.e. outputting wisdom files) by using another `conda` environment. 

Previously, the compiling is quite messy (i.e. I don't recognize many flags) when I use my py21cmfast `conda` environment:
```
/home/yqin/3rd_party/envs/py21cmfast/bin/x86_64-conda_cos6-linux-gnu-cc -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/yqin/3rd_party/envs/py21cmfast/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/yqin/3rd_party/envs/py21cmfast/include -fPIC -I/media/dprelogovic/81614149-2ed8-4c76-82e1-c46763d086fa/yqin/bitbucket/21cmfast.org/21cmFAST/src/py21cmfast/src -I/home/yqin/3rd_party/envs/py21cmfast/include/python3.6m -c build/temp.linux-x86_64-3.6/py21cmfast.c_21cmfast.c -o build/temp.linux-x86_64-3.6/build/temp.linux-x86_64-3.6/py21cmfast.c_21cmfast.o -fopenmp -Ofast -w
/home/yqin/3rd_party/envs/py21cmfast/bin/x86_64-conda_cos6-linux-gnu-gcc -pthread -shared -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,/home/yqin/3rd_party/envs/py21cmfast/lib -L/home/yqin/3rd_party/envs/py21cmfast/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,/home/yqin/3rd_party/envs/py21cmfast/lib -L/home/yqin/3rd_party/envs/py21cmfast/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/yqin/3rd_party/envs/py21cmfast/lib -Wl,-rpath-link,/home/yqin/3rd_party/envs/py21cmfast/lib -L/home/yqin/3rd_party/envs/py21cmfast/lib -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/yqin/3rd_party/envs/py21cmfast/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/yqin/3rd_party/envs/py21cmfast/include build/temp.linux-x86_64-3.6/build/temp.linux-x86_64-3.6/py21cmfast.c_21cmfast.o -L/home/yqin/3rd_party/lib:/home/yqin/3rd_party/lib: -L/home/yqin/3rd_party/envs/py21cmfast/bin/x86_64-conda_cos6-linux-gnu-gcc-ranlib -L/home/yqin/3rd_party/envs/py21cmfast/bin/x86_64-conda_cos6-linux-gnu-ranlib -lm -lgsl -lgslcblas -lfftw3f_omp -lfftw3f -o build/lib.linux-x86_64-3.6/py21cmfast/c_21cmfast.abi3.so
```
In this case, the shared object dependencies of `build/lib.linux-x86_64-3.6/py21cmfast/c_21cmfast.abi3.so` is 
```
        linux-vdso.so.1 (0x00007ffcd2ba2000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7f900e1000)
        libgsl.so.23 => /home/yqin/3rd_party/envs/py21cmfast/lib/libgsl.so.23 (0x00007f7f8fc5e000)
        libgslcblas.so.0 => /home/yqin/3rd_party/envs/py21cmfast/lib/libgslcblas.so.0 (0x00007f7f8fa17000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7f8f7f8000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7f8f407000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f7f90683000)
```

However, when I use the base `conda` environment, I got 
```
gcc -pthread -B /home/yqin/3rd_party/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/media/dprelogovic/81614149-2ed8-4c76-82e1-c46763d086fa/yqin/bitbucket/21cmfast.org/21cmFAST/src/py21cmfast/src -I/home/yqin/3rd_party/include/python3.6m -c build/temp.linux-x86_64-3.6/py21cmfast.c_21cmfast.c -o build/temp.linux-x86_64-3.6/build/temp.linux-x86_64-3.6/py21cmfast.c_21cmfast.o -fopenmp -Ofast -w 
gcc -pthread -shared -B /home/yqin/3rd_party/compiler_compat -L/home/yqin/3rd_party/lib -Wl,-rpath=/home/yqin/3rd_party/lib -Wl,--no-as-needed -Wl,--sysroot=/ -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/yqin/3rd_party/envs/py21cmfast/lib -Wl,-rpath-link,/home/yqin/3rd_party/envs/py21cmfast/lib -L/home/yqin/3rd_party/envs/py21cmfast/lib build/temp.linux-x86_64-3.6/build/temp.linux-x86_64-3.6/py21cmfast.c_21cmfast.o -L/home/yqin/3rd_party/envs/py21cmfast/bin/x86_64-conda_cos6-linux-gnu-ranlib -L/home/yqin/3rd_party/lib:/home/yqin/3rd_party/lib: -L/home/yqin/3rd_party/envs/py21cmfast/bin/x86_64-conda_cos6-linux-gnu-gcc-ranlib -lm -lgsl -lgslcblas -lfftw3f_omp -lfftw3f -o build/lib.linux-x86_64-3.6/py21cmfast/c_21cmfast.abi3.so
```
and 
```
        linux-vdso.so.1 (0x00007ffecfb98000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5e9fbdf000)
        libgsl.so.25 => /home/yqin/3rd_party/lib/libgsl.so.25 (0x00007f5e9f8e3000)
        libopenblas.so.0 => /home/yqin/3rd_party/lib/libopenblas.so.0 (0x00007f5e9dca3000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5e9da84000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5e9d693000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f5ea0385000)
        libgfortran.so.4 => /home/yqin/3rd_party/lib/./libgfortran.so.4 (0x00007f5e9d369000)
        libgomp.so.1 => /home/yqin/3rd_party/lib/./libgomp.so.1 (0x00007f5ea0556000)
        libquadmath.so.0 => /home/yqin/3rd_party/lib/././libquadmath.so.0 (0x00007f5ea051c000)
        libgcc_s.so.1 => /home/yqin/3rd_party/lib/././libgcc_s.so.1 (0x00007f5ea0508000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f5e9d161000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5e9cf5d000)
```
I'm guessing some of the flags that are automatically added to cc in the first place could be the problem. I'll try to remove them in the first case and see if it helps.

**Comment by qyx268** [comment] 2021-01-03 15:06
I tried a bit more and start to think it is probably the version of gcc install of fftw that is causing the bug, because apparently in both `conda` environments, I installed fftw manually rather than using `conda install`.

In my py21cmfast environment, I have 
```
gcc_impl_linux-64         7.3.0                habb00fd_1    anaconda  
gcc_linux-64              7.3.0                h553295d_9    anaconda
```
This, I think..., was because googling `conda install gcc` only returned the package for OSX. So I used the google result of `conda install gcc linux`...

In the base environment, I have
```
gcc                       4.8.5                         7    https://repo.anaconda.com/pkgs/free
```
I don't remember how I got this version though... It is likely just there by default...

Travis (https://travis-ci.com/github/21cmfast/21cmFAST/builds/206089458) seems to be using gcc 5.4... So I also tried in py21cmfast environment`https://anaconda.org/psi4/gcc-5`. It is gcc 5.2 though... and it failed reporting `unrecognized command line option ‘-fno-plt’`. I then tried `https://anaconda.org/asmeurer/gcc` (GCC 4.8.5). Same error plus `unrecognized command line option ‘-fstack-protector-strong’ `. It seems that `-fno-plt` is supported starting GCC 6. I don't know why it is added when gcc-5/4 is used. It is probably caused by `libgcc-ng                 9.3.0` that is required by the `python`...

**Comment by steven-murray** [comment] 2021-01-04 15:57
How did you print out those dependencies? 

I just created a new environment and didn't install any gcc into it (so using the base gcc on my system I guess) and it prints this in the compilation commands:

```
gcc -pthread -B /home/steven/.conda/envs/21cmfasttmp/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/tmp/pip-req-build-niv1oitf/src/py21cmfast/src -I/home/steven/.conda/envs/21cmfasttmp/include/python3.8 -c build/temp.linux-x86_64-3.8/py21cmfast.c_21cmfast.c -o build/temp.linux-x86_64-3.8/build/temp.linux-x86_64-3.8/py21cmfast.c_21cmfast.o -fopenmp -Ofast -w
  gcc -pthread -shared -B /home/steven/.conda/envs/21cmfasttmp/compiler_compat -L/home/steven/.conda/envs/21cmfasttmp/lib -Wl,-rpath=/home/steven/.conda/envs/21cmfasttmp/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.8/build/temp.linux-x86_64-3.8/py21cmfast.c_21cmfast.o -lm -lgsl -lgslcblas -lfftw3f_omp -lfftw3f -o build/lib.linux-x86_64-3.8/py21cmfast/c_21cmfast.abi3.so
```

When I run the original example, it still doesn't make a wisdom file. My gcc version is `10.2.0`. I believe this used to work for me -- perhaps on gcc 9? I'll check it out

**Comment by qyx268** [comment] 2021-01-04 16:00
I used `ldd`

**Comment by steven-murray** [comment] 2021-01-04 16:02
Hmmm, that printed nothing for me

**Comment by steven-murray** [comment] 2021-01-04 16:29
Not sure how relevant this is, but I'll put it here.

I first tried installing gcc via `conda`: `conda install -c anaconda gcc_linux-64`, printing out the `--version` of this compiler gives

```
x86_64-conda_cos6-linux-gnu-cc (crosstool-NG 1.23.0.449-a04d0) 7.3.0
```

Upon recompiling 21cmFAST, I have to manually set the paths for `fftw` and `gsl` (because using the `conda` gcc seems to overwrite the default INC and LIB paths). I also checked which version of gcc is being used to compile my system FFTW -- it is `10.1.0`. Anyway, recompiling 21cmFAST also gives no wisdom output. 

Then I tried installing FFTW and GSL via `conda-forge` (along with the conda `gcc` I already installed above). I checked which GCC version they were compiled with,  and it is 7.5.0.

So.... not really sure what all that means :-/

**Comment by steven-murray** [comment] 2021-01-07 16:50
Note that #199 implemented a workaround for this (i.e. just use FFTW_ESTIMATE if we can't find the wisdom file). But it doesn't fix the basic problem of actually getting the wisdoms to work.

After a little bit of reading around, it seems that fftw keeps its own collected wisdom in-memory. If we just don't "forget" it, could we just use that per-session, rather than writing to files?

**Comment by qyx268** [comment] 2021-01-07 17:08
An unrelated thing about using FFTW: when I was doing the timing estimate, I did find creating FFTW wisdom files can take a while if DIM is very large. Therefore it might be better to just swich off FFTW in this case...

I cant find wisdom in-memory, what are you referring to? But I remember I tried `fftw_export_wisdom_to_string`, which also failed. Or you are taking about `fftw_import_system_wisdom`?

**Comment by steven-murray** [comment] 2021-01-07 19:58
Does creating the FFTW wisdom file take longer than estimating the plan? 

I *think* that if you create a plan, the wisdom is stored somewhere in FFTW's memory. You can write it out to file, but you could also just leave it in memory. Of course, writing to file means you can use it again in the next session, but I'm not sure how much of an improvement that is (maybe it is for large boxes where you want to run multiple simulations separately). Yeah, the other thing is we could write it to the system FFTW storage and import it from there. I presume at the moment that the wisdom itself is not being created properly, and even that won't work.

**Comment by qyx268** [comment] 2021-01-08 14:00
I assume outputting the file takes just a second because they are usually pretty small. Most time should be spent on estimating the plan.

hmm... The question is whether the current bug crashes at outputting the file or at creating the plan... But I agree we dont actually really need to store the plan if not doing mcmc...

**Comment by steven-murray** [comment] 2021-01-08 15:04
I think the bug is in creating the plan -- the plan is NULL after creation.

**Comment by qyx268** [comment] 2021-01-10 17:19
finally have some clue... 

For the standalone code @steven-murray  showed above, I do get output from `fftwf_print_plan` if I compile with flags in the following order:
`gcc a.c -L/media/yqin/81614149-2ed8-4c76-82e1-c46763d086fa/yqin/3rd_party/envs/py21cmfast/lib/ -lm -lfftw3f_omp -lfftw3f -lgsl -lgslcblas`
or even just 
`gcc a.c -L/media/yqin/81614149-2ed8-4c76-82e1-c46763d086fa/yqin/3rd_party/envs/py21cmfast/lib/ -lfftw3f`

However, if I add `-lgslcblas` before `-lfftw3f`, `fftwf_print_plan` will print nothing. e.g.
`gcc a.c -L/media/yqin/81614149-2ed8-4c76-82e1-c46763d086fa/yqin/3rd_party/envs/py21cmfast/lib/ -lm -lfftw3f_omp -lgslcblas -lfftw3f -lgsl`

@steven-murray, Can you confirm this on your side?

PS. removeing gslcblas from `build_cffi.py` doesn't seem to work though...

**Comment by qyx268** [comment] 2021-01-10 18:50
I'm guessing that installing `fftw` with float and openmp supported needs `mkl_fft`, which is why `mkl` is included in `environment_dev.yml`. After recreating the environment with `mkl` package removed, further `conda uninstall mkl`, and manually installing `fftw`, I managed to fix this bug.

I guess we can suggest users to follow this step when `CreateFFTWWisdoms` fails to create the wisdom files...

@steven-murray  could you please also confirm whether this works for you or not?

**Comment by steven-murray** [comment] 2021-01-11 18:12
Awesome nice job @qyx268 .

I am in the middle of moving house and won't be able to check this until Wednesday, but it looks promising. When you say "manually install" do you mean with conda or via Ubuntu package manager?

**Comment by qyx268** [comment] 2021-01-11 18:34
I meant installing from the source ftp://ftp.fftw.org/pub/fftw/fftw-3.3.8.zip

**Comment by qyx268** [comment] 2021-01-11 18:35
happy moving btw!

**Comment by steven-murray** [comment] 2021-01-14 23:02
I can confirm that removing `mkl` fixed this for me. Indeed, all I needed to do was `conda uninstall mkl` then `pip install 21cmFAST`. Unfortunately, removing `mkl` also removed the conda packages for `scipy`, `astropy` and a bunch of others, which were then re-installed via the `pip` command. Not sure what this means for our `conda` package of 21cmFAST...

**Comment by qyx268** [comment] 2021-01-14 23:11
ah, those packages (e.g. `scipy` `astropy`) are the reason even if I removed `mkl_fft` from `environment_dev.yml`, I still get `mkl` in my environment... 

What's the best way to resolve this issue then? Certainly building the environment by oneself is a straightforward way to avoid using `mkl`. Also, we can just suggest people to `pip install` rather than `conda install`... But this doesn't feel right. Can we specify `conda install` to avoid using `mkl` even for `scipy`, `astropy`, etc?

Also, I wonder if there is an easy way to report this to probably `mkl` and ask them to solve it?

**Comment by qyx268** [comment] 2021-01-14 23:12
https://docs.anaconda.com/mkl-optimizations/
Looks like we just need to include `nomkl` in the yml file?

**Comment by qyx268** [comment] 2021-01-14 23:16
perhaps we could ask for help from `mkl_fft`? I don't see any obvious existing issues that cover it...
https://github.com/IntelPython/mkl_fft/issues?q=is%3Aissue+is%3Aclosed?

**Comment by steven-murray** [comment] 2021-01-14 23:24
Ah nice. Yeah, perhaps we should create an issue. In the meantime, I'll add the `nomkl` option to the conda package.

**Comment by qyx268** [comment] 2021-01-20 17:55
I can confirm that adding nomkl in environment_dev.yml and removing mkl, mkl_random, and mkl_fft from it solve the problem. It's just that users will have to install fftw by themselves.

**Comment by steven-murray** [comment] 2021-02-04 21:38
Done.

**Closed by steven-murray** 2021-02-04 21:38 UTC
Labels: context: C backend, context: error-handling, status: requires discussion
