### ISSUE TITLE
More informative error 

### ISSUE THREAD

**Issue by qyx268** [21cmfast/21cmFAST#189] opened 2020-10-30 17:40 UTC
**Is your feature request related to a problem? Please describe.**

It came to us (@JulianBMunoz ) that when setting BOX_LEN to a very small value (e.g. 25 for testing codes), the program crashes and reports 
`ParameterError: 21cmFAST does not support this combination of parameters.`

**Describe the solution you'd like**

It should be more informative, e.g. providing information of which part of the parameter set is not supported (in this case, BOX_LEN cannot be this small)

**Describe alternatives you've considered**

**Additional context**

@JulianBMunoz  was also trapped by setting `USE_MINI_HALOS=True` (which automatically set `USE_MASS_DEPENDENT_ZETA=True`) without setting `USE_INTERPOLATION_TABLES=True`, supporting the idea proposed in #186 that we should provide information of this...

**Comment by steven-murray** [comment] 2020-10-30 19:08
Agreed. That is a poor error message!

**Comment by dprelogo** [comment] 2021-01-16 12:32
I'm creating a small database, pulling samples from the following [prior.pdf](https://github.com/21cmfast/21cmFAST/files/5824360/prior.pdf) and getting the same error in ~5-10% of cases: `py21cmfast._utils.ParameterError: 21cmFAST does not support this combination of parameters.`
In the following file are parameters used for runs that failed. Not specified are default ones. [failed.txt](https://github.com/21cmfast/21cmFAST/files/5824358/failed.txt)

Do you see something weird about those runs?

**Comment by BradGreig** [comment] 2021-01-18 05:27
Hi @dprelogo, there are no obvious issues with the parameter values themselves. I tried running the second parameter combination from the failed list and it worked without issue on my machine (i.e. laptop). Which version are you running?

It is possible that there is an issue with the parameter combination and/or the evaluation of one of the interpolation tables. I would recommend running one of the failed models with full logging (compiling with LOG_DEBUG etc.) to try and see if that helps identify where it occurs (ionisation/spin temperature etc.).

**Comment by steven-murray** [comment] 2021-02-04 21:39
Also related to #134

**Comment by dprelogo** [comment] 2021-02-24 18:25
Hi @BradGreig, I followed your advice and made a run after compiling with `LOG_LEVEL=DEBUG`, for one set of parameters, using different machine and setup. I'm attaching the (truncated) [output](https://github.com/21cmfast/21cmFAST/files/6038013/simple_run.txt) of a simple [run](https://github.com/21cmfast/21cmFAST/files/6038048/simple_run_script.txt) which fails on both machines.

Number of simulations that failed is now large enough that I made a [corner plot](https://github.com/21cmfast/21cmFAST/files/6037982/unfinalized.pdf). `alpha_star = 0.5, alpha_esc = -0.5, t_star = 0.5` are fixed. 
I know that this part of parameter space is not so important (very small `E_0`), but I guess it's not expected that the code fails there...

**Comment by andreimesinger** [comment] 2021-02-24 18:29
most of those are not xrays and the code was not designed for that regime.  but it shouldn’t crash...

**Comment by BradGreig** [comment] 2021-02-25 00:58
Hi @dprelogo, thanks for the update. I can confirm that the model you provided in your simple run does fail for me too. This will allow me to go digging into what is happening, and hopefully is the source of all the failures shown in your corner plot. I've always looked at NU_X_THRESH > 100 - 200 (so not surprised NU_X_THRESH = 11 causes issues). I wonder if it might be a L_X - NU_X_THRESH combination that causes the failure.

I'll let you know if I discover anything useful!

**Comment by BradGreig** [comment] 2021-02-25 07:57
Hey @dprelogo @andreimesinger, I was able to narrow down the source. @andreimesinger it is caused by the function `nu_tau_one`. This (and likely most of these models) are resulting in `x_e ~ 1` which causes the function to exit. That is the average free electron fraction from calculating T_S in the previous snapshot becomes `x_e ~ 1`. In v2 21cmFAST this would exit with the error `Ts.c: WARNING: x_e value is too close to 1 for convergence in nu_tau_one`.

What appears to be happening is that there is a sudden jump to `x_e ~ 1`. The snapshot previously is always quite far from one (~0.2-0.3). There appears to be rapid changes to the output from `integrate_over_nu` around where this transition to `x_e ~ 1` occurs. I think these models are fairly extreme in producing excess electron fractions (high L_X (10^42) and low NU_X_THRESH (10)). I don't think it is a numerical error in the evaluation of `integrate_over_nu` for the interpolation tables but I'm not sure.

@andreimesinger, thoughts on what behaviour you want this to have? At some level if `x_e ~ 1` then it doesn't really matter what the result is as xHI ~ 0. However, I guess with recombinations it might be possible to have voxels with xHI > 0 in which T_S is necessary (though again, it is highly likely that T_S >> T_CMB at this stage anyway). Maybe rather than exiting this condition, we can set a "sensible" value for a returned value for `nu_tau_one`. Though I don't know what this sensible value needs to be.

**Comment by andreimesinger** [comment] 2021-02-25 09:59
thanks brad!  i think the user should be prevented from setting E0 below 100eV...  it is an xray threshold and it doesn’t make sense to set it to values in the UV; the reionization code deals with these photons.

but more generally, if the ionized fraction is close to 1, then nu_tau_one should be set to some arbitrarily large value...  the xrays do not interact with the IGM in this case.  i though there was already a flag somewhere to check for this and avoid the unneeded calculations, but perhaps i am mistaken.

**Comment by andreimesinger** [comment] 2021-02-25 22:07
> On 05.02.2021, at 10:59, Andrei Mesinger <andrei.mesinger@sns.it> wrote:
> 
> but more generally, if the ionized fraction is close to 1, then nu_tau_one should be set to some arbitrarily large value... 


sorry, i was thinking of the mean free path —> infinity.  nu_tau_one would go towards zero, i.e. E_0 in this case.

> 
> 
>

**Comment by BradGreig** [comment] 2021-02-25 23:37
Hey @andreimesinger, can I just clarify. Do you mean set `lower_int_limit = NU_X_THRESH` rather than doing the FMAX of `nu_tau_one` and `NU_X_THRESH`?

There was a commented out piece of code for this in v2 (with a seemingly unused flag of `DO_NOT_COMPARE_NUS`). So it may have appeared in some version a while back (or you thought of implementing it) but has never been used.

**Comment by andreimesinger** [comment] 2021-02-25 23:41
> On 05.02.2021, at 00:37, BradGreig <notifications@github.com> wrote:
> 
> 
> Hey @andreimesinger <https://github.com/andreimesinger>, can I just clarify. Do you mean set lower_int_limit = NU_X_THRESH rather than doing the FMAX of nu_tau_one and NU_X_THRESH?
> 
> 

yes, or have nu_tau_one return nu_x_thresh (since I am not sure you know a-priory that you are in that situation)

**Comment by BradGreig** [comment] 2021-02-25 23:56
Yeah, good point

**Comment by BradGreig** [comment] 2021-03-24 01:35
Closing this following #219

**Closed by BradGreig** 2021-03-24 01:35 UTC
Labels: context: python wrapper, status: requires discussion, type: maintenance
